package it.water.connectors.hbase.service;

import it.water.connectors.hbase.api.HBaseConnectorSystemApi;
import it.water.connectors.hbase.api.options.HBaseConnectorOptions;
import it.water.core.api.interceptors.OnActivate;
import it.water.core.api.interceptors.OnDeactivate;
import it.water.core.api.registry.filter.ComponentFilterBuilder;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.core.interceptors.annotations.Inject;
import it.water.core.service.BaseSystemServiceImpl;
import lombok.Setter;
import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.hbase.HBaseConfiguration;
import org.apache.hadoop.hbase.TableName;
import org.apache.hadoop.hbase.client.*;
import org.apache.hadoop.hbase.filter.Filter;
import org.apache.hadoop.hbase.filter.FilterList;
import org.apache.hadoop.hbase.security.provider.SimpleSaslAuthenticationProvider;
import org.apache.hadoop.hbase.util.Bytes;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicLong;
import java.util.function.BiConsumer;
import java.util.function.Consumer;

/**
 * @Generated by Water Generator
 * System service API class for HBaseConnector integration service.
 */
@FrameworkComponent
public class HBaseConnectorSystemServiceImpl extends BaseSystemServiceImpl implements HBaseConnectorSystemApi {

    @Inject
    @Setter
    private ComponentFilterBuilder componentFilterBuilder;

    @Inject
    @Setter
    private HBaseConnectorOptions hbaseConnectorOptions;

    private Configuration configuration;
    private Admin admin;
    private Connection connection;
    private int maxScanPageSize;
    private ExecutorService hbaseThreadPool;

    @OnActivate
    public void activate() {
        initHBaseThreadPool();
        Thread connectionThread = new Thread(() -> {
            try {
                setHBaseConfiguration();
                connection = ConnectionFactory.createConnection(configuration);
                admin = connection.getAdmin();
            } catch (IOException e) {
                getLog().error(e.getMessage(), e);
            }
        });
        connectionThread.start();
    }

    @OnDeactivate
    public void deactivate() throws InterruptedException {
        this.hbaseThreadPool.shutdown();
        try {
            long awaitTermination = hbaseConnectorOptions != null ? hbaseConnectorOptions.getAwaitTermination() : 1000L;
            if (!this.hbaseThreadPool.awaitTermination(awaitTermination, TimeUnit.MILLISECONDS)) {
                this.hbaseThreadPool.shutdownNow();
            }
        } catch (InterruptedException e) {
            this.hbaseThreadPool.shutdownNow();
            throw e;
        }
        closeResources();
    }

    private void closeResources() {
        try {
            if (admin != null) {
                admin.close();
            }
        } catch (IOException e) {
            getLog().warn("Unable to close HBase admin", e);
        }
        try {
            if (connection != null) {
                connection.close();
            }
        } catch (IOException e) {
            getLog().warn("Unable to close HBase connection", e);
        }
    }

    private void initHBaseThreadPool() {
        int corePoolSize = hbaseConnectorOptions != null ? hbaseConnectorOptions.getCorePoolSize() : 10;
        int maximumPoolSize = hbaseConnectorOptions != null ? hbaseConnectorOptions.getMaximumPoolSize() : 20;
        long keepAlive = hbaseConnectorOptions != null ? hbaseConnectorOptions.getKeepAliveTime() : 0L;
        this.hbaseThreadPool = new ThreadPoolExecutor(
            corePoolSize,
            maximumPoolSize,
            keepAlive,
            TimeUnit.MILLISECONDS,
            new LinkedBlockingQueue<>()
        );
    }

    @Override
    public void executeTask(Runnable runnableTask) {
        this.hbaseThreadPool.execute(runnableTask);
    }

    @Override
    public void checkConnection() throws IOException {
        HBaseAdmin.available(configuration);
    }

    @Override
    public void createTable(String tableName, List<String> columnFamilies) {
        Runnable r = () -> {
            TableName table = TableName.valueOf(tableName);
            TableDescriptorBuilder tableDescriptorBuilder = TableDescriptorBuilder.newBuilder(table);
            columnFamilies.forEach(columnFamily ->
                tableDescriptorBuilder.setColumnFamily(
                    ColumnFamilyDescriptorBuilder.newBuilder(Bytes.toBytes(columnFamily)).build()
                )
            );
            try {
                admin.createTable(tableDescriptorBuilder.build());
            } catch (IOException e) {
                HBaseConnectorSystemServiceImpl.this.getLog().error(e.getMessage(), e);
            }
        };
        wrapInsideHBaseConnectorClassLoader(r);
    }

    @Override
    public void createTableAsync(String tableName, List<String> columnFamilies) {
        this.executeTask(() -> this.createTable(tableName, columnFamilies));
    }

    @Override
    public void deleteData(String tableName, String rowKey) {
        Runnable r = () -> {
            try {
                Table table = connection.getTable(TableName.valueOf(tableName));
                Delete delete = new Delete(Bytes.toBytes(rowKey));
                table.delete(delete);
                table.close();
            } catch (IOException e) {
                HBaseConnectorSystemServiceImpl.this.getLog().error(e.getMessage(), e);
            }
        };
        wrapInsideHBaseConnectorClassLoader(r);
    }

    @Override
    public void deleteDataAsync(String tableName, String rowKey) {
        this.executeTask(() -> this.deleteData(tableName, rowKey));
    }

    @Override
    public void disableTable(String tableName) {
        Runnable r = () -> {
            try {
                admin.disableTable(TableName.valueOf(tableName));
            } catch (IOException e) {
                HBaseConnectorSystemServiceImpl.this.getLog().error(e.getMessage(), e);
            }
        };
        wrapInsideHBaseConnectorClassLoader(r);
    }

    @Override
    public void disableTableAsync(String tableName) {
        this.executeTask(() -> disableTable(tableName));
    }

    @Override
    public void disableAndDropTable(String tableName) {
        Runnable r = () -> {
            try {
                admin.disableTable(TableName.valueOf(tableName));
                admin.deleteTable(TableName.valueOf(tableName));
            } catch (IOException e) {
                HBaseConnectorSystemServiceImpl.this.getLog().error(e.getMessage(), e);
            }
        };
        wrapInsideHBaseConnectorClassLoader(r);
    }

    @Override
    public void disableAndDropTableAsync(String tableName) {
        this.executeTask(() -> disableAndDropTable(tableName));
    }

    @Override
    public void dropTable(String tableName) {
        Runnable r = () -> {
            try {
                admin.deleteTable(TableName.valueOf(tableName));
            } catch (IOException e) {
                HBaseConnectorSystemServiceImpl.this.getLog().error(e.getMessage(), e);
            }
        };
        wrapInsideHBaseConnectorClassLoader(r);
    }

    @Override
    public void dropTableAsync(String tableName) {
        this.executeTask(() -> dropTable(tableName));
    }

    @Override
    public void enableTable(String tableName) {
        Runnable r = () -> {
            try {
                admin.enableTable(TableName.valueOf(tableName));
            } catch (IOException e) {
                HBaseConnectorSystemServiceImpl.this.getLog().error(e.getMessage(), e);
            }
        };
        wrapInsideHBaseConnectorClassLoader(r);
    }

    @Override
    public void insertData(String tableName, String rowKey, String columnFamily, String column, String cellValue) {
        Runnable r = () -> {
            try {
                Table table = connection.getTable(TableName.valueOf(tableName));
                Put put = new Put(rowKey.getBytes());
                put.addColumn(columnFamily.getBytes(), column.getBytes(), cellValue.getBytes());
                table.put(put);
                table.close();
            } catch (IOException e) {
                HBaseConnectorSystemServiceImpl.this.getLog().error(e.getMessage(), e);
            }
        };
        wrapInsideHBaseConnectorClassLoader(r);
    }

    @Override
    public void insertDataAsync(String tableName, String rowKey, String columnFamily, String column, String cellValue) {
        this.executeTask(() -> insertData(tableName, rowKey, columnFamily, column, cellValue));
    }

    /**
     * @deprecated
     *
     * @param tableName
     * @param columns
     * @param rowKeyLowerBound
     * @param rowKeyUpperBound
     * @param limit
     * @return
     * @throws IOException
     */
    @Deprecated
    public ResultScanner getScanner(
        String tableName,
        Map<byte[], List<byte[]>> columns,
        byte[] rowKeyLowerBound,
        byte[] rowKeyUpperBound,
        int limit
    ) throws IOException {
        Table table = connection.getTable(TableName.valueOf(tableName));
        Scan scan = getScan(columns, rowKeyLowerBound, rowKeyUpperBound, limit, null);
        return table.getScanner(scan);
    }

    private Scan getScan(
        Map<byte[], List<byte[]>> columns,
        byte[] rowKeyLowerBound,
        byte[] rowKeyUpperBound,
        int limit,
        List<Filter> extraFilters
    ) {
        List<Filter> rowFilterList = new ArrayList<>();
        Scan scan = new Scan();
        if (rowKeyLowerBound != null && rowKeyLowerBound.length > 0) {
            scan.withStartRow(rowKeyLowerBound, true);
        }
        if (rowKeyUpperBound != null && rowKeyUpperBound.length > 0) {
            scan.withStopRow(rowKeyUpperBound, true);
        }
        getLog().debug("Querying HBase with limit: {}", limit);
        int maxResults = 0;
        if (limit > 0 && limit <= maxScanPageSize)
            maxResults = limit;
        else if (limit <= 0)
            maxResults = -1;
        else maxResults = maxScanPageSize;
        getLog().debug("HBase scan limit: {}", maxResults);
        if (maxResults > 0) {
            scan.setLimit(maxResults);
        }

        for (Map.Entry<byte[], List<byte[]>> entry : columns.entrySet()) {
            byte[] columnFamily = entry.getKey();
            List<byte[]> columnList = entry.getValue();

            if (columnList == null || columnList.isEmpty()) {
                scan.addFamily(columnFamily);
            } else {
                for (byte[] column : columnList) {
                    scan.addColumn(columnFamily, column);
                }
            }
        }

        if (extraFilters != null) {
            rowFilterList.addAll(extraFilters);
        }
        if (!rowFilterList.isEmpty()) {
            scan.setFilter(new FilterList(FilterList.Operator.MUST_PASS_ALL, rowFilterList));
        }

        return scan;
    }

    @Override
    public long rowCount(String tableName, byte[] columnFamily, byte[] column, byte[] rowKeyLowerBound, byte[] rowKeyUpperBound)
        throws Throwable {
        Map<byte[], List<byte[]>> columns = new HashMap<>();
        columns.put(columnFamily, new ArrayList<>());
        if (column != null) {
            columns.get(columnFamily).add(column);
        }
        return rowCount(tableName, columns, rowKeyLowerBound, rowKeyUpperBound);
    }

    @Override
    public long rowCount(String tableName, Map<byte[], List<byte[]>> columns, byte[] rowKeyLowerBound, byte[] rowKeyUpperBound) {
        AtomicLong counter = new AtomicLong();
        scanResults(tableName, columns, rowKeyLowerBound, rowKeyUpperBound, -1, result ->
            counter.set(counter.addAndGet(result.listCells().size()))
        );
        return counter.longValue();
    }

    @Override
    public List<byte[]> scan(String tableName, byte[] columnFamily, byte[] column, byte[] rowKeyLowerBound, byte[] rowKeyUpperBound) {
        Map<byte[], List<byte[]>> columns = new HashMap<>();
        columns.put(columnFamily, new ArrayList<>());
        columns.get(columnFamily).add(column);
        List<byte[]> cells = new ArrayList<>();
        scanResults(tableName, columns, rowKeyLowerBound, rowKeyUpperBound, 0, result ->
            cells.add(result.getValue(columnFamily, column))
        );
        return cells;
    }

    public List<Result> scanWithCompleteResult(
        String tableName,
        Map<byte[], List<byte[]>> columns,
        byte[] rowKeyLowerBound,
        byte[] rowKeyUpperBound,
        int limit
    ) {
        List<Result> results = new ArrayList<>();
        scanResults(tableName, columns, rowKeyLowerBound, rowKeyUpperBound, limit, results::add);
        return results;
    }

    @Override
    public Map<byte[], Map<byte[], Map<byte[], byte[]>>> scan(
        String tableName,
        Map<byte[], List<byte[]>> columns,
        byte[] rowKeyLowerBound,
        byte[] rowKeyUpperBound,
        int limit
    ) {
        Map<byte[], Map<byte[], Map<byte[], byte[]>>> output = new HashMap<>();
        scanResults(tableName, columns, rowKeyLowerBound, rowKeyUpperBound, limit, result -> {
            byte[] rowKey = result.getRow();
            Map<byte[], Map<byte[], byte[]>> rowMap = new HashMap<>();
            output.put(rowKey, rowMap);
            for (Map.Entry<byte[], List<byte[]>> entry : columns.entrySet()) {
                byte[] columnFamily = entry.getKey();
                List<byte[]> requestedColumns = entry.getValue();
                Map<byte[], byte[]> familyMap = new HashMap<>();
                rowMap.put(columnFamily, familyMap);
                if (requestedColumns == null) {
                    continue;
                }
                for (byte[] column : requestedColumns) {
                    byte[] value = result.getValue(columnFamily, column);
                    if (value != null) {
                        familyMap.put(column, value);
                    }
                }
            }
        });

        return output;
    }

    private void setHBaseConfiguration() {
        configuration = createHBaseBasicConf();
        maxScanPageSize = hbaseConnectorOptions != null ? hbaseConnectorOptions.getMaxScanPageSize() : Integer.MAX_VALUE;
    }

    private Configuration createHBaseBasicConf() {
        Configuration c = HBaseConfiguration.create();

        String masterHostname = hbaseConnectorOptions != null ? hbaseConnectorOptions.getMasterHostname() : "localhost";
        int masterPort = hbaseConnectorOptions != null ? hbaseConnectorOptions.getMasterPort() : 16000;

        c.setBoolean(
            "hbase.cluster.distributed",
            hbaseConnectorOptions != null && hbaseConnectorOptions.getClusterDistributed()
        );
        c.set("hbase.master", masterHostname + ":" + masterPort);
        c.set("hbase.master.hostname", masterHostname);
        c.setInt("hbase.master.info.port", hbaseConnectorOptions != null ? hbaseConnectorOptions.getMasterInfoPort() : 16010);
        c.setInt("hbase.master.port", masterPort);
        c.setInt("hbase.regionserver.info.port", hbaseConnectorOptions != null ? hbaseConnectorOptions.getRegionserverInfoPort() : 16030);
        c.setInt("hbase.regionserver.port", hbaseConnectorOptions != null ? hbaseConnectorOptions.getRegionserverPort() : 16020);
        c.set("hbase.rootdir", hbaseConnectorOptions != null ? hbaseConnectorOptions.getRootdir() : "hdfs://localhost:8020/hbase");
        c.set("hbase.zookeeper.quorum", hbaseConnectorOptions != null ? hbaseConnectorOptions.getZookeeperQuorum() : "localhost");
        return c;
    }

    @Override
    public boolean tableExists(String tableName) {
        AtomicBoolean exists = new AtomicBoolean(false);
        Runnable r = () -> {
            try {
                exists.set(admin.tableExists(TableName.valueOf(tableName)));
            } catch (IOException e) {
                HBaseConnectorSystemServiceImpl.this.getLog().error(e.getMessage(), e);
            }
        };
        wrapInsideHBaseConnectorClassLoader(r);
        return exists.get();
    }

    public void scanResults(
        String tableName,
        Map<byte[], List<byte[]>> columns,
        byte[] rowKeyLowerBound,
        byte[] rowKeyUpperBound,
        int limit,
        Consumer<Result> consumerFunction
    ) {
        ClassLoader originalClassLoader = Thread.currentThread().getContextClassLoader();
        ClassLoader thisClassLoader = SimpleSaslAuthenticationProvider.class.getClassLoader();
        Thread.currentThread().setContextClassLoader(thisClassLoader);
        try {
            ResultScanner scanner = getScanner(tableName, columns, rowKeyLowerBound, rowKeyUpperBound, limit);
            for (Result result : scanner) {
                consumerFunction.accept(result);
            }
        } catch (Throwable t) {
            getLog().error(t.getMessage(), t);
        } finally {
            Thread.currentThread().setContextClassLoader(originalClassLoader);
        }
    }

    public void iterateOverResults(
        String tableName,
        Map<byte[], List<byte[]>> columns,
        byte[] rowKeyLowerBound,
        byte[] rowKeyUpperBound,
        int limit,
        BiConsumer<Result, Boolean> consumerFunction
    ) {
        ClassLoader originalClassLoader = Thread.currentThread().getContextClassLoader();
        ClassLoader thisClassLoader = SimpleSaslAuthenticationProvider.class.getClassLoader();
        Thread.currentThread().setContextClassLoader(thisClassLoader);
        try {
            ResultScanner scanner = getScanner(tableName, columns, rowKeyLowerBound, rowKeyUpperBound, limit);
            Iterator<Result> it = scanner.iterator();
            while (it.hasNext()) {
                Result r = it.next();
                boolean hasMoreElements = it.hasNext();
                consumerFunction.accept(r, hasMoreElements);
            }
        } catch (Throwable t) {
            getLog().error(t.getMessage(), t);
        } finally {
            Thread.currentThread().setContextClassLoader(originalClassLoader);
        }
    }

    private void wrapInsideHBaseConnectorClassLoader(Runnable r) {
        ClassLoader originalClassLoader = Thread.currentThread().getContextClassLoader();
        ClassLoader thisClassLoader = SimpleSaslAuthenticationProvider.class.getClassLoader();
        Thread.currentThread().setContextClassLoader(thisClassLoader);
        try {
            r.run();
        } catch (Exception e) {
            getLog().error(e.getMessage(), e);
        } finally {
            Thread.currentThread().setContextClassLoader(originalClassLoader);
        }
    }
}
