package it.water.connectors.hbase.service.rest;

import it.water.connectors.hbase.api.HBaseConnectorApi;
import it.water.connectors.hbase.api.rest.HBaseConnectorRestApi;
import it.water.core.api.service.rest.FrameworkRestController;
import it.water.core.interceptors.annotations.Inject;
import lombok.Setter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.ws.rs.core.Response;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

/**
 * @Generated by Water Generator
 * Rest API class for HBaseConnector integration service.
 */
@FrameworkRestController(referredRestApi = HBaseConnectorRestApi.class)
public class HBaseConnectorRestControllerImpl implements HBaseConnectorRestApi {

    private static final Logger LOG = LoggerFactory.getLogger(HBaseConnectorRestControllerImpl.class);

    @Inject
    @Setter
    private HBaseConnectorApi hbaseConnectorApi;

    @Override
    public String checkConnection() throws IOException {
        LOG.debug("Invoking /hbase/checkConnection");
        hbaseConnectorApi.checkConnection();
        return "Connection OK";
    }

    @Override
    public Response checkModuleWorking() {
        LOG.debug("Invoking /hbase/module/status");
        return Response.ok("HBaseConnector Module works!").build();
    }

    @Override
    public void createTable(String tableName, String columnFamilies) throws IOException {
        LOG.debug("Invoking /hbase/tables - Creating table {}", tableName);
        List<String> families = Arrays.asList(columnFamilies.split(","));
        hbaseConnectorApi.createTable(tableName, families);
    }

    @Override
    public void insertData(String tableName, String rowKey, String columnFamily, String column, String cellValue)
        throws IOException {
        LOG.debug("Invoking /hbase/tables - Inserting into table {}", tableName);
        hbaseConnectorApi.insertData(tableName, rowKey, columnFamily, column, cellValue);
    }

    @Override
    public void deleteData(String tableName, String rowKey) throws IOException {
        LOG.debug("Invoking /hbase/tables/rows - Deleting from table {}", tableName);
        hbaseConnectorApi.deleteData(tableName, rowKey);
    }

    @Override
    public void enableTable(String tableName) throws IOException {
        LOG.debug("Invoking /hbase/tables/{}/enable - Enabling table", tableName);
        hbaseConnectorApi.enableTable(tableName);
    }

    @Override
    public void disableTable(String tableName) throws IOException {
        LOG.debug("Invoking /hbase/tables/{}/disable - Disabling table", tableName);
        hbaseConnectorApi.disableTable(tableName);
    }

    @Override
    public void dropTable(String tableName) throws IOException {
        LOG.debug("Invoking /hbase/tables/{} - Dropping table", tableName);
        hbaseConnectorApi.dropTable(tableName);
    }
}
